// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: Futuristic_Ebike

#ifndef _FUTURISTIC_EBIKE_UI_H
#define _FUTURISTIC_EBIKE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lv_ui_assets.h"
#include "lvgl.h"

void Particle1_Animation(lv_obj_t * TargetObject, int delay);
void Particle2_Animation(lv_obj_t * TargetObject, int delay);
void Particle3_Animation(lv_obj_t * TargetObject, int delay);
void Fash_Animation(lv_obj_t * TargetObject, int delay);
void Wave1_Animation(lv_obj_t * TargetObject, int delay);
void Wave2_Animation(lv_obj_t * TargetObject, int delay);
void Off_Animation(lv_obj_t * TargetObject, int delay);
void On_Animation(lv_obj_t * TargetObject, int delay);
void ui_sw_event_cb(lv_event_t * e);
extern lv_obj_t * ui_Group_Battery_Indicator;
extern lv_obj_t * ui_Particle_Group;
extern lv_obj_t * ui_Image_Particle1;
extern lv_obj_t * ui_Image_Particle2;
extern lv_obj_t * ui_Image_Particle3;
extern lv_obj_t * ui_Wave_Group;
extern lv_obj_t * ui_Wave1;
extern lv_obj_t * ui_Wave2;
extern lv_obj_t * ui_Image_Battery_BG;
extern lv_obj_t * ui_Image_Flash;
extern lv_obj_t * ui____initial_actions0;
extern lv_obj_t * cb1;
extern lv_obj_t * sw;
extern lv_obj_t * list1;

void ui_init(lv_obj_t * ui_Driving);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
