// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "max31856_task.h"

lv_obj_t *Achart;
lv_obj_t *Bchart;
lv_chart_series_t *Achartx;
lv_chart_series_t *Acharty;
// lv_chart_series_t *chartz;
lv_obj_t *Ax_label;
lv_obj_t *Ay_label;
lv_chart_series_t *Bchartx;
lv_chart_series_t *Bcharty;
// lv_chart_series_t *chartz;
lv_obj_t *Bx_label;
lv_obj_t *By_label;
// lv_obj_t *z_label;
static void chart1_timer_cb(lv_timer_t *timer);
static void chart2_timer_cb(lv_timer_t *timer);

lv_obj_t *Acoldlabel;
lv_obj_t *Atherlabel;
lv_obj_t *Bcoldlabel;
lv_obj_t *Btherlabel;
static void digital_timer_cb(lv_timer_t *timer);

void ui_HomePage_screen_init(void)
{
    ui_HomePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_TabView1 = lv_tabview_create(ui_HomePage, LV_DIR_BOTTOM, 40);
    lv_obj_set_width(ui_TabView1, 240);
    lv_obj_set_height(ui_TabView1, 320);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_img_src(ui_TabView1, &ui_img_99_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x080C10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(lv_tabview_get_tab_btns(ui_TabView1), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(lv_tabview_get_tab_btns(ui_TabView1), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_btns(ui_TabView1), LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x0AC2A4), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &ui_font_DigitalFont22b1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(lv_tabview_get_tab_btns(ui_TabView1), LV_BLEND_MODE_ADDITIVE, LV_PART_ITEMS | LV_STATE_DEFAULT);

    static lv_style_t style; // 创建style
    lv_style_init(&style);   // 初始化style
    // lv_style_set_border_width(&style, 0); // 设置样式边框宽度
    lv_style_set_border_side(&style, LV_BORDER_SIDE_NONE); // 设置样式边框显示范围

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Chart1");

    lv_obj_set_scrollbar_mode(ui_TabPage1, LV_SCROLLBAR_MODE_OFF); // 禁止滚动条
    lv_obj_clear_flag(ui_TabPage1, LV_OBJ_FLAG_SCROLLABLE);        // 清除可滚动标志

    lv_obj_t *chart_panel = lv_obj_create(ui_TabPage1);
    lv_obj_add_style(chart_panel, &style, 0); // 将样式添加到对象中
    lv_obj_set_size(chart_panel, 240 - 10, 270);
    lv_obj_align(chart_panel, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_bg_color(chart_panel, lv_palette_main(LV_PALETTE_GREY), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(chart_panel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_scrollbar_mode(chart_panel, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_clear_flag(chart_panel, LV_OBJ_FLAG_SCROLLABLE); // 清除可滚动标志
    /*
        LV_PART_MAIN：可以用来修改背景和栅格线的样式。参考3.1
        LV_PART_SCROLLBAR：当放大的时候，会绘制ScrollBar。参考3.2
        LV_PART_ITEMS：对应series画的线或柱状图。参考3.3
        LV_PART_INDICATOR：对应ITEMS上的点。参考3.4
        LV_PART_CURSOR：对应光标。参考3.5
        LV_PART_TICKS：对应记号和标签。参考3.6
    */
    Achart = lv_chart_create(chart_panel);
    lv_timer_create(chart1_timer_cb, 10, NULL); // 每0.1秒钟更新一次 chart 的显示
    // lv_obj_set_style_line_width(chart, 10, LV_PART_ITEMS);

    lv_obj_set_size(Achart, 240 - 30 - 30, 270 - 10);
    lv_obj_set_style_width(Achart, 0, LV_PART_INDICATOR); // 图表标点大小
    lv_obj_set_style_height(Achart, 0, LV_PART_INDICATOR);
    lv_obj_set_style_line_color(Achart, lv_palette_main(LV_PALETTE_BLUE_GREY), LV_PART_MAIN); // 图表格栅颜色
    lv_obj_set_style_border_color(Achart, lv_palette_main(LV_PALETTE_ORANGE), LV_PART_MAIN);  // 图表边框颜色
    lv_obj_set_style_bg_color(Achart, lv_palette_main(LV_PALETTE_ORANGE), LV_PART_SCROLLBAR); // 滚动条颜色
    // lv_obj_set_style_bg_color(Achart, lv_palette_main(LV_PALETTE_BLUE_GREY), LV_PART_MAIN);    // 图表背景颜色
    lv_obj_set_style_bg_color(Achart, lv_palette_main(LV_PALETTE_GREY), LV_PART_MAIN | LV_STATE_DEFAULT); // 图表背景颜色
    lv_obj_set_style_bg_opa(Achart, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                                // 图表背景颜色
    lv_obj_align(Achart, LV_ALIGN_CENTER, 17, 0);

    lv_chart_set_point_count(Achart, 300);                                         // 设置为300个点显示
    lv_chart_set_div_line_count(Achart, 10, 5);                                    // 设施栅格数
    lv_chart_set_axis_tick(Achart, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 9, 3, true, 46); // 设置记号和标签
    // lv_obj_set_style_line_color(Achart, lv_palette_main(LV_PALETTE_ORANGE), LV_PART_TICKS);   // 设置记号颜色
    lv_obj_set_style_text_color(Achart, lv_color_hex(0xFFFFFF), LV_PART_TICKS); // 设置标签颜色

    lv_chart_set_zoom_x(Achart, 256 * 1); // x缩放.256表示原大小
    lv_chart_set_zoom_y(Achart, 256 * 1); // y缩放.256表示原大小

    // cursor = lv_chart_add_cursor(Achart, lv_palette_main(LV_PALETTE_GREEN), LV_DIR_ALL);   // 添加光标
    // lv_obj_set_style_width(Achart, 5, LV_PART_CURSOR);   // 设置光标点的大小
    // lv_obj_set_style_height(Achart, 5, LV_PART_CURSOR);  // 设置光标点的大小
    // lv_point_t point = {50, 50};
    // lv_chart_set_cursor_pos(Achart, cursor, &point); // 设置光标相对于 chart 的坐标（不会随着滚动条变化）

    Achartx = lv_chart_add_series(Achart, lv_color_hex(0xE214D3), LV_CHART_AXIS_PRIMARY_Y);
    Acharty = lv_chart_add_series(Achart, lv_color_hex(0x0FBDB8), LV_CHART_AXIS_PRIMARY_Y);
    // Achartz = lv_chart_add_series(Achart, lv_palette_main(LV_PALETTE_GREEN), LV_CHART_AXIS_PRIMARY_Y);

    // lv_chart_set_next_value(Achart, ser1, 200);
    // static const lv_coord_t value[] = { 0, 100, 300, 0, 100, 300, 0, 100, 300, 0};
    // lv_chart_set_ext_y_array(Achart, chartSer1, (lv_coord_t*)value);

    Ax_label = lv_label_create(Achart);
    lv_obj_align(Ax_label, LV_ALIGN_TOP_LEFT, 10, 0);
    lv_label_set_text(Ax_label, "ColdJ: 0.00 C");
    lv_obj_set_style_text_color(Ax_label, lv_color_hex(0xE214D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(Ax_label, &ui_font_DigitalFont22b1, LV_PART_MAIN | LV_STATE_DEFAULT);

    Ay_label = lv_label_create(Achart);
    lv_obj_align(Ay_label, LV_ALIGN_TOP_LEFT, 10, 20);
    lv_label_set_text(Ay_label, "TherC: 0.00 C");
    lv_obj_set_style_text_color(Ay_label, lv_color_hex(0x0FBDB8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(Ay_label, &ui_font_DigitalFont22b1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // z_label = lv_label_create(chart);
    // lv_obj_align(z_label, LV_ALIGN_TOP_LEFT, 168, 30);
    // lv_label_set_text(z_label, "Z: 0.00");
    // lv_obj_set_style_text_color(z_label, lv_palette_main(LV_PALETTE_GREEN), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(z_label, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Digital");
    lv_obj_set_scrollbar_mode(ui_TabPage2, LV_SCROLLBAR_MODE_OFF); // 禁止滚动条
    lv_obj_clear_flag(ui_TabPage2, LV_OBJ_FLAG_SCROLLABLE);        // 清除可滚动标志

    lv_obj_t *panel = lv_obj_create(ui_TabPage2);
    lv_obj_add_style(panel, &style, 0); // 将样式添加到对象中
    lv_obj_set_size(panel, 220, 120);
    lv_obj_align(panel, LV_ALIGN_TOP_MID, 0, 0);
    lv_obj_set_style_bg_color(panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(panel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_scrollbar_mode(panel, LV_SCROLLBAR_MODE_OFF); // 禁止滚动条
    lv_obj_clear_flag(panel, LV_OBJ_FLAG_SCROLLABLE);        // 清除可滚动标志

    lv_timer_create(digital_timer_cb, 500, NULL); // 每0.5秒钟更新一次label的显示

    lv_obj_t *label = lv_label_create(panel);
    lv_obj_align(label, LV_ALIGN_TOP_LEFT, 0, 0);
    lv_label_set_text(label, "1");
    lv_obj_set_style_text_color(label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &ui_font_DigitalFont30b1, LV_PART_MAIN | LV_STATE_DEFAULT);
    label = lv_label_create(panel);
    lv_style_set_border_width(&style, 5); // 设置样式边框宽度
    lv_obj_align(label, LV_ALIGN_TOP_MID, 0, 0);
    lv_label_set_text(label, "THERMOCOUPLE");
    lv_obj_set_style_text_color(label, lv_color_hex(0xE214D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &ui_font_DigitalFont22b1, LV_PART_MAIN | LV_STATE_DEFAULT);
    Atherlabel = lv_label_create(panel);
    lv_obj_align(Atherlabel, LV_ALIGN_CENTER, 0, -11);
    lv_label_set_text(Atherlabel, "100.00 C");
    lv_obj_set_style_text_color(Atherlabel, lv_color_hex(0x0FBDB8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(Atherlabel, &ui_font_DigitalFont30b1, LV_PART_MAIN | LV_STATE_DEFAULT);
    label = lv_label_create(panel);
    lv_obj_align(label, LV_ALIGN_TOP_MID, 0, 52);
    lv_label_set_text(label, "COLDJUNCTION");
    lv_obj_set_style_text_color(label, lv_color_hex(0xE214D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &ui_font_DigitalFont22b1, LV_PART_MAIN | LV_STATE_DEFAULT);
    Acoldlabel = lv_label_create(panel);
    lv_obj_align(Acoldlabel, LV_ALIGN_CENTER, 0, 40);
    lv_label_set_text(Acoldlabel, "100.00 C");
    lv_obj_set_style_text_color(Acoldlabel, lv_color_hex(0x0FBDB8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(Acoldlabel, &ui_font_DigitalFont30b1, LV_PART_MAIN | LV_STATE_DEFAULT);

    panel = lv_obj_create(ui_TabPage2);
    lv_obj_add_style(panel, &style, 0); // 将样式添加到对象中
    lv_obj_set_size(panel, 220, 120);
    lv_obj_align(panel, LV_ALIGN_TOP_MID, 0, 135);
    lv_obj_set_style_bg_color(panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(panel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_scrollbar_mode(panel, LV_SCROLLBAR_MODE_OFF); // 禁止滚动条
    lv_obj_clear_flag(panel, LV_OBJ_FLAG_SCROLLABLE);        // 清除可滚动标志
    label = lv_label_create(panel);
    lv_obj_align(label, LV_ALIGN_TOP_LEFT, 0, 0);
    lv_label_set_text(label, "2");
    lv_obj_set_style_text_color(label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &ui_font_DigitalFont30b1, LV_PART_MAIN | LV_STATE_DEFAULT);
    label = lv_label_create(panel);
    lv_obj_align(label, LV_ALIGN_TOP_MID, 0, 0);
    lv_label_set_text(label, "THERMOCOUPLE");
    lv_obj_set_style_text_color(label, lv_color_hex(0xE214D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &ui_font_DigitalFont22b1, LV_PART_MAIN | LV_STATE_DEFAULT);
    Btherlabel = lv_label_create(panel);
    lv_obj_align(Btherlabel, LV_ALIGN_CENTER, 0, -11);
    lv_label_set_text(Btherlabel, "100.00 C");
    lv_obj_set_style_text_color(Btherlabel, lv_color_hex(0x0FBDB8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(Btherlabel, &ui_font_DigitalFont30b1, LV_PART_MAIN | LV_STATE_DEFAULT);
    label = lv_label_create(panel);
    lv_obj_align(label, LV_ALIGN_TOP_MID, 0, 52);
    lv_label_set_text(label, "COLDJUNCTION");
    lv_obj_set_style_text_color(label, lv_color_hex(0xE214D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &ui_font_DigitalFont22b1, LV_PART_MAIN | LV_STATE_DEFAULT);
    Bcoldlabel = lv_label_create(panel);
    lv_obj_align(Bcoldlabel, LV_ALIGN_CENTER, 0, 40);
    lv_label_set_text(Bcoldlabel, "100.00 C");
    lv_obj_set_style_text_color(Bcoldlabel, lv_color_hex(0x0FBDB8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(Bcoldlabel, &ui_font_DigitalFont30b1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Chart2");

    // lv_obj_t *label = lv_label_create(ui_TabPage3);
    // lv_label_set_long_mode(label, LV_LABEL_LONG_SCROLL_CIRCULAR);
    // lv_label_set_text(label, "Inertial-Measurement-Unit: JY901B");

    lv_obj_set_scrollbar_mode(ui_TabPage3, LV_SCROLLBAR_MODE_OFF); // 禁止滚动条
    lv_obj_clear_flag(ui_TabPage3, LV_OBJ_FLAG_SCROLLABLE);        // 清除可滚动标志

    chart_panel = lv_obj_create(ui_TabPage3);
    lv_obj_add_style(chart_panel, &style, 0); // 将样式添加到对象中
    lv_obj_set_size(chart_panel, 240 - 10, 270);
    lv_obj_align(chart_panel, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_bg_color(chart_panel, lv_palette_main(LV_PALETTE_GREY), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(chart_panel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_scrollbar_mode(chart_panel, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_clear_flag(chart_panel, LV_OBJ_FLAG_SCROLLABLE); // 清除可滚动标志
    /*
        LV_PART_MAIN：可以用来修改背景和栅格线的样式。参考3.1
        LV_PART_SCROLLBAR：当放大的时候，会绘制ScrollBar。参考3.2
        LV_PART_ITEMS：对应series画的线或柱状图。参考3.3
        LV_PART_INDICATOR：对应ITEMS上的点。参考3.4
        LV_PART_CURSOR：对应光标。参考3.5
        LV_PART_TICKS：对应记号和标签。参考3.6
    */
    Bchart = lv_chart_create(chart_panel);
    lv_timer_create(chart2_timer_cb, 10, NULL); // 每0.1秒钟更新一次 chart 的显示
    // lv_obj_set_style_line_width(chart, 10, LV_PART_ITEMS);

    lv_obj_set_size(Bchart, 240 - 30 - 30, 270 - 10);
    lv_obj_set_style_width(Bchart, 0, LV_PART_INDICATOR); // 图表标点大小
    lv_obj_set_style_height(Bchart, 0, LV_PART_INDICATOR);
    lv_obj_set_style_line_color(Bchart, lv_palette_main(LV_PALETTE_BLUE_GREY), LV_PART_MAIN); // 图表格栅颜色
    lv_obj_set_style_border_color(Bchart, lv_palette_main(LV_PALETTE_ORANGE), LV_PART_MAIN);  // 图表边框颜色
    lv_obj_set_style_bg_color(Bchart, lv_palette_main(LV_PALETTE_ORANGE), LV_PART_SCROLLBAR); // 滚动条颜色
    // lv_obj_set_style_bg_color(Bchart, lv_palette_main(LV_PALETTE_BLUE_GREY), LV_PART_MAIN);    // 图表背景颜色
    lv_obj_set_style_bg_color(Bchart, lv_palette_main(LV_PALETTE_GREY), LV_PART_MAIN | LV_STATE_DEFAULT); // 图表背景颜色
    lv_obj_set_style_bg_opa(Bchart, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                                // 图表背景颜色
    lv_obj_align(Bchart, LV_ALIGN_CENTER, 17, 0);

    lv_chart_set_point_count(Bchart, 300);                                         // 设置为300个点显示
    lv_chart_set_div_line_count(Bchart, 10, 5);                                    // 设施栅格数
    lv_chart_set_axis_tick(Bchart, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 9, 3, true, 46); // 设置记号和标签
    // lv_obj_set_style_line_color(Bchart, lv_palette_main(LV_PALETTE_ORANGE), LV_PART_TICKS);   // 设置记号颜色
    lv_obj_set_style_text_color(Bchart, lv_color_hex(0xFFFFFF), LV_PART_TICKS); // 设置标签颜色

    lv_chart_set_zoom_x(Bchart, 256 * 1); // x缩放.256表示原大小
    lv_chart_set_zoom_y(Bchart, 256 * 1); // y缩放.256表示原大小

    // cursor = lv_chart_add_cursor(Bchart, lv_palette_main(LV_PALETTE_GREEN), LV_DIR_ALL);   // 添加光标
    // lv_obj_set_style_width(Bchart, 5, LV_PART_CURSOR);   // 设置光标点的大小
    // lv_obj_set_style_height(Bchart, 5, LV_PART_CURSOR);  // 设置光标点的大小
    // lv_point_t point = {50, 50};
    // lv_chart_set_cursor_pos(Bchart, cursor, &point); // 设置光标相对于 chart 的坐标（不会随着滚动条变化）

    Bchartx = lv_chart_add_series(Bchart, lv_color_hex(0xE214D3), LV_CHART_AXIS_PRIMARY_Y);
    Bcharty = lv_chart_add_series(Bchart, lv_color_hex(0x0FBDB8), LV_CHART_AXIS_PRIMARY_Y);
    // chartz = lv_chart_add_series(Bchart, lv_palette_main(LV_PALETTE_GREEN), LV_CHART_AXIS_PRIMARY_Y);

    // lv_chart_set_next_value(Bchart, ser1, 200);
    // static const lv_coord_t value[] = { 0, 100, 300, 0, 100, 300, 0, 100, 300, 0};
    // lv_chart_set_ext_y_array(Bchart, chartSer1, (lv_coord_t*)value);

    Bx_label = lv_label_create(Bchart);
    lv_obj_align(Bx_label, LV_ALIGN_TOP_LEFT, 10, 0);
    lv_label_set_text(Bx_label, "ColdJ: 0.00 C");
    lv_obj_set_style_text_color(Bx_label, lv_color_hex(0xE214D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(Bx_label, &ui_font_DigitalFont22b1, LV_PART_MAIN | LV_STATE_DEFAULT);

    By_label = lv_label_create(Bchart);
    lv_obj_align(By_label, LV_ALIGN_TOP_LEFT, 10, 20);
    lv_label_set_text(By_label, "TherC: 0.00 C");
    lv_obj_set_style_text_color(By_label, lv_color_hex(0x0FBDB8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(By_label, &ui_font_DigitalFont22b1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // z_label = lv_label_create(chart);
    // lv_obj_align(z_label, LV_ALIGN_TOP_LEFT, 168, 30);
    // lv_label_set_text(z_label, "Z: 0.00");
    // lv_obj_set_style_text_color(z_label, lv_palette_main(LV_PALETTE_GREEN), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(z_label, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 将指定的 ui_TabPage2 对象滚动到可见区域，使用带有动画效果的方式
    lv_obj_scroll_to_view_recursive(ui_TabPage2, LV_ANIM_ON);
}

static void chart1_timer_cb(lv_timer_t *timer)
{

    // static unsigned long int x_time = 0;
    static float y_x = 0.00;
    static float y_y = 0.00;
    // static float y_z = 0.0;

    y_x = max31856_A.coldjunction_c * 10;
    y_y = max31856_A.thermocouple_c * 10;
    // y_z = ;
    lv_chart_set_range(Achart, LV_CHART_AXIS_PRIMARY_Y, 0.00 * 10, 500.00 * 10); // 设置加速度测量范围 ACC

    lv_chart_set_next_value(Achart, Achartx, y_x);
    // lv_obj_set_style_line_width(chart, 10, LV_PART_ITEMS);
    lv_chart_set_next_value(Achart, Acharty, y_y);
    // lv_obj_set_style_line_width(chart, 10, LV_PART_ITEMS);
    // lv_chart_set_next_value(chart, chartz, y_z);
    /* CJ图例 */
    char x_label_buf[21];
    sprintf(x_label_buf, "ColdJ: %.2f C", y_x / 10);
    lv_label_set_text(Ax_label, x_label_buf);
    /* TMC图例 */
    char y_label_buf[21];
    sprintf(y_label_buf, "TherC: %.2f C", y_y / 10);
    lv_label_set_text(Ay_label, y_label_buf);
    // /* Z轴图例 */
    // char z_label_buf[10];
    // sprintf(z_label_buf, "Z: %.2f", y_z);
    // lv_label_set_text(z_label, z_label_buf);
    /* X轴时间轴加1 */
    // x_time += 1;
}

static void chart2_timer_cb(lv_timer_t *timer)
{

    // static unsigned long int x_time = 0;
    static float y_x = 0.00;
    static float y_y = 0.00;
    // static float y_z = 0.0;

    y_x = max31856_B.coldjunction_c * 10;
    y_y = max31856_B.thermocouple_c * 10;
    // y_z = ;
    lv_chart_set_range(Bchart, LV_CHART_AXIS_PRIMARY_Y, 0.00 * 10, 500.00 * 10); // 设置加速度测量范围 ACC

    lv_chart_set_next_value(Bchart, Bchartx, y_x);
    // lv_obj_set_style_line_width(chart, 10, LV_PART_ITEMS);
    lv_chart_set_next_value(Bchart, Bcharty, y_y);
    // lv_obj_set_style_line_width(chart, 10, LV_PART_ITEMS);
    // lv_chart_set_next_value(chart, chartz, y_z);
    /* CJ图例 */
    char x_label_buf[21];
    sprintf(x_label_buf, "ColdJ: %.2f C", y_x / 10);
    lv_label_set_text(Bx_label, x_label_buf);
    /* TMC图例 */
    char y_label_buf[21];
    sprintf(y_label_buf, "TherC: %.2f C", y_y / 10);
    lv_label_set_text(By_label, y_label_buf);
    // /* Z轴图例 */
    // char z_label_buf[10];
    // sprintf(z_label_buf, "Z: %.2f", y_z);
    // lv_label_set_text(z_label, z_label_buf);
    /* X轴时间轴加1 */
    // x_time += 1;
}

static void digital_timer_cb(lv_timer_t *timer)
{

    static int AcoldX100 = 0;
    static int AtherX100 = 0;
    AcoldX100 = max31856_A.coldjunction_c * 100;
    AtherX100 = max31856_A.thermocouple_c * 100;

    static int BcoldX100 = 0;
    static int BtherX100 = 0;
    BcoldX100 = max31856_B.coldjunction_c * 100;
    BtherX100 = max31856_B.thermocouple_c * 100;

    // 格式化字符串
    char Acold[10];
    sprintf(Acold, "%.2f C", AcoldX100 / 100.00);
    char Ather[10];
    sprintf(Ather, "%.2f C", AtherX100 / 100.00);

    char Bcold[10];
    sprintf(Bcold, "%.2f C", BcoldX100 / 100.00);
    char Bther[10];
    sprintf(Bther, "%.2f C", BtherX100 / 100.00);
    // 更新label的显示文本
    lv_label_set_text(Acoldlabel, Acold);
    lv_label_set_text(Atherlabel, Ather);

    lv_label_set_text(Bcoldlabel, Bcold);
    lv_label_set_text(Btherlabel, Bther);
}