// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void StartUpLogoFade_Animation( lv_obj_t *TargetObject, int delay);
void StartUpLogoEmerge_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_StartPage
void ui_StartPage_screen_init(void);
void ui_event_StartPage( lv_event_t * e);
extern lv_obj_t *ui_StartPage;
extern lv_obj_t *ui_Logo;
// SCREEN: ui_HomePage
void ui_HomePage_screen_init(void);
extern lv_obj_t *ui_HomePage;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_TabPage1;
extern lv_obj_t *ui_TabPage2;
extern lv_obj_t *ui_TabPage3;
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_logo1_png);   // assets\logo1.png
LV_IMG_DECLARE( ui_img_99_png);   // assets\99.png

LV_FONT_DECLARE( ui_font_DigitalFont22b1);
LV_FONT_DECLARE( ui_font_DigitalFont30b1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
